fullnameOverride: customerapi
replicaCount: 1
image:
  repository: __Repository__
  tag: __BuildNumber__
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: acr-secret

service:
  type: ClusterIP
  port: 80

deployment:
  containerPort: 80

probes:
  enabled: true

ingress:
  enabled: __IngressEnabled__
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  namespace: __K8sNamespace__
  path: /  
  pathType: Prefix
  hosts:
    - __URL__
  tls:
    - secretName: __TlsSecretName__
      hosts:
        - __URL__
    
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  averageCpuUtilization: 50

secrets:
  connectionstrings:
    ConnectionStrings__CustomerDatabase: __ConnectionString__
    AzureServiceBus__ConnectionString: __AzureServiceBusConnectionString__

resources:
   limits:
    cpu: 0.3
    memory: 128Mi
   requests:
    cpu: 100m
    memory: 64Mi
nodeSelector: {}

tolerations: []

affinity: {}

envvariables:
  TenantId: __TenantId__
# useAadAuthentication: __UseAadAuthentication__

#aadAuthentication:
#  managedIdentityId: __ManagedIdentityId__
#  managedIdentityClientId: __ManagedIdentityClientId__  
#  managedIdentityName: __Managedidentity-aks__